Create table annual_deaths_only
Select Year , executions, 
Meningitis, 
Alzheimer, 
Parkinson, 
Nutritional_deficiencies, 
Malaria, 
Drowning, 
Interpersonal_violence, 
Maternal_disorders, 
HIV, 
Drug_use_disorders, 
Tuberculosis, 
Cardiovascular_diseases, 
Lower_respiratory_infections, 
Neonatal_disorders, 
Alcohol_use_disorders, 
Self_harm, 
Exposure_to_forces_of_nature, 
Diarrheal_diseases, 
Environmental_heat_and_cold_exposure, 
Neoplasms, 
Conflict_and_terrorism, 
Diabetes_mellitus, 
Chronic_kidney_disease, 
Poisonings, 
Protein_energy_malnutrition, 
Terrorism, 
Road_injuries, 
Chronic_respiratory_diseases, 
Cirrhosis_and_other_chronic_liver_diseases, 
Digestive_diseases, 
Fire_heat_and_hot_substances, 
Acute_hepatitis
From AnnuallyDeaths

